#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDSoftPiebm")]
	public partial class BDSoftPiebmDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertMENSAJE(MENSAJE instance);
    partial void UpdateMENSAJE(MENSAJE instance);
    partial void DeleteMENSAJE(MENSAJE instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    #endregion
		
		public BDSoftPiebmDataContext() : 
				base(global::Datos.Properties.Settings.Default.BDSoftPiebmConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDSoftPiebmDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSoftPiebmDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSoftPiebmDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSoftPiebmDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MENSAJE> MENSAJE
		{
			get
			{
				return this.GetTable<MENSAJE>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTO
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarEstadoMensaje")]
		public int cp_ActualizarEstadoMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMensaje", DbType="Int")] System.Nullable<int> idMensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMensaje, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarVistaUsuario")]
		public ISingleResult<cp_ListarVistaUsuarioResult> cp_ListarVistaUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarVistaUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarProducto")]
		public int cp_ActualizarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Producto", DbType="VarChar(50)")] string producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ubicacion", DbType="VarChar(50)")] string ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioAprox", DbType="Decimal(5,2)")] System.Nullable<decimal> precioAprox)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, producto, estado, ubicacion, cantidad, descripcion, fecha, precioAprox);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarProducto")]
		public int cp_EliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarUsuario")]
		public int cp_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarMensaje")]
		public int cp_InsertarMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remitente", DbType="VarChar(50)")] string remitente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(200)")] string mensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, remitente, mensaje, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarProducto")]
		public int cp_InsertarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Producto", DbType="VarChar(50)")] string producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ubicacion", DbType="VarChar(50)")] string ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioAprx", DbType="Decimal(5,2)")] System.Nullable<decimal> precioAprx)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), producto, estado, ubicacion, cantidad, descripcion, fecha, precioAprx);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarUsuario")]
		public int cp_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ocupacion", DbType="VarChar(20)")] string ocupacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrase", DbType="VarChar(50)")] string contrase)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, ocupacion, email, contrase);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarMensaje")]
		public ISingleResult<cp_ListarMensajeResult> cp_ListarMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarMensajeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarProducto")]
		public ISingleResult<cp_ListarProductoResult> cp_ListarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarReporteMensaje")]
		public ISingleResult<cp_ListarReporteMensajeResult> cp_ListarReporteMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarReporteMensajeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarUsuario")]
		public ISingleResult<cp_ListarUsuarioResult> cp_ListarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarVistaMensaje")]
		public ISingleResult<cp_ListarVistaMensajeResult> cp_ListarVistaMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarVistaMensajeResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENSAJE")]
	public partial class MENSAJE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Mensaje;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Remitente;
		
		private string _Mensaje1;
		
		private string _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MensajeChanging(int value);
    partial void OnID_MensajeChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnRemitenteChanging(string value);
    partial void OnRemitenteChanged();
    partial void OnMensaje1Changing(string value);
    partial void OnMensaje1Changed();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public MENSAJE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Mensaje", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Mensaje
		{
			get
			{
				return this._ID_Mensaje;
			}
			set
			{
				if ((this._ID_Mensaje != value))
				{
					this.OnID_MensajeChanging(value);
					this.SendPropertyChanging();
					this._ID_Mensaje = value;
					this.SendPropertyChanged("ID_Mensaje");
					this.OnID_MensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remitente", DbType="VarChar(50)")]
		public string Remitente
		{
			get
			{
				return this._Remitente;
			}
			set
			{
				if ((this._Remitente != value))
				{
					this.OnRemitenteChanging(value);
					this.SendPropertyChanging();
					this._Remitente = value;
					this.SendPropertyChanged("Remitente");
					this.OnRemitenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Mensaje", Storage="_Mensaje1", DbType="VarChar(200)")]
		public string Mensaje1
		{
			get
			{
				return this._Mensaje1;
			}
			set
			{
				if ((this._Mensaje1 != value))
				{
					this.OnMensaje1Changing(value);
					this.SendPropertyChanging();
					this._Mensaje1 = value;
					this.SendPropertyChanged("Mensaje1");
					this.OnMensaje1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Usuario;
		
		private string _Usuario1;
		
		private string _Ocupación;
		
		private string _Email;
		
		private string _Contraseña;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UsuarioChanging(int value);
    partial void OnID_UsuarioChanged();
    partial void OnUsuario1Changing(string value);
    partial void OnUsuario1Changed();
    partial void OnOcupaciónChanging(string value);
    partial void OnOcupaciónChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="VarChar(100)")]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this.OnUsuario1Changing(value);
					this.SendPropertyChanging();
					this._Usuario1 = value;
					this.SendPropertyChanged("Usuario1");
					this.OnUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupación", DbType="VarChar(20)")]
		public string Ocupación
		{
			get
			{
				return this._Ocupación;
			}
			set
			{
				if ((this._Ocupación != value))
				{
					this.OnOcupaciónChanging(value);
					this.SendPropertyChanging();
					this._Ocupación = value;
					this.SendPropertyChanged("Ocupación");
					this.OnOcupaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Producto;
		
		private string _Producto1;
		
		private string _Estado;
		
		private string _Ubicación;
		
		private System.Nullable<int> _Cantidad;
		
		private string _Descripción;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _Precio_Aproximado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProductoChanging(int value);
    partial void OnID_ProductoChanged();
    partial void OnProducto1Changing(string value);
    partial void OnProducto1Changed();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnUbicaciónChanging(string value);
    partial void OnUbicaciónChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnPrecio_AproximadoChanging(System.Nullable<decimal> value);
    partial void OnPrecio_AproximadoChanged();
    #endregion
		
		public PRODUCTO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Producto", Storage="_Producto1", DbType="VarChar(50)")]
		public string Producto1
		{
			get
			{
				return this._Producto1;
			}
			set
			{
				if ((this._Producto1 != value))
				{
					this.OnProducto1Changing(value);
					this.SendPropertyChanging();
					this._Producto1 = value;
					this.SendPropertyChanged("Producto1");
					this.OnProducto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50)")]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this.OnUbicaciónChanging(value);
					this.SendPropertyChanging();
					this._Ubicación = value;
					this.SendPropertyChanged("Ubicación");
					this.OnUbicaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(200)")]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Aproximado", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Precio_Aproximado
		{
			get
			{
				return this._Precio_Aproximado;
			}
			set
			{
				if ((this._Precio_Aproximado != value))
				{
					this.OnPrecio_AproximadoChanging(value);
					this.SendPropertyChanging();
					this._Precio_Aproximado = value;
					this.SendPropertyChanged("Precio_Aproximado");
					this.OnPrecio_AproximadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cp_ListarVistaUsuarioResult
	{
		
		private int _ID_Usuario;
		
		private string _Usuario;
		
		private string _Ocupación;
		
		public cp_ListarVistaUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="Int NOT NULL")]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this._ID_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupación", DbType="VarChar(20)")]
		public string Ocupación
		{
			get
			{
				return this._Ocupación;
			}
			set
			{
				if ((this._Ocupación != value))
				{
					this._Ocupación = value;
				}
			}
		}
	}
	
	public partial class cp_ListarMensajeResult
	{
		
		private int _ID_Mensaje;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Remitente;
		
		private string _Mensaje;
		
		private string _Estado;
		
		public cp_ListarMensajeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Mensaje", DbType="Int NOT NULL")]
		public int ID_Mensaje
		{
			get
			{
				return this._ID_Mensaje;
			}
			set
			{
				if ((this._ID_Mensaje != value))
				{
					this._ID_Mensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remitente", DbType="VarChar(50)")]
		public string Remitente
		{
			get
			{
				return this._Remitente;
			}
			set
			{
				if ((this._Remitente != value))
				{
					this._Remitente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(200)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class cp_ListarProductoResult
	{
		
		private int _ID_Producto;
		
		private string _Producto;
		
		private string _Estado;
		
		private string _Ubicación;
		
		private System.Nullable<int> _Cantidad;
		
		private string _Descripción;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _Precio_Aproximado;
		
		public cp_ListarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int NOT NULL")]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					this._ID_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50)")]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this._Ubicación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(200)")]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Aproximado", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Precio_Aproximado
		{
			get
			{
				return this._Precio_Aproximado;
			}
			set
			{
				if ((this._Precio_Aproximado != value))
				{
					this._Precio_Aproximado = value;
				}
			}
		}
	}
	
	public partial class cp_ListarReporteMensajeResult
	{
		
		private int _ID_Producto;
		
		private string _Producto;
		
		private string _Estado;
		
		private string _Ubicación;
		
		private System.Nullable<int> _Cantidad;
		
		private string _Descripción;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _Precio_Aproximado;
		
		private string _Usuario;
		
		private string _Ocupación;
		
		private string _Email;
		
		public cp_ListarReporteMensajeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int NOT NULL")]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					this._ID_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50)")]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this._Ubicación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(200)")]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Aproximado", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Precio_Aproximado
		{
			get
			{
				return this._Precio_Aproximado;
			}
			set
			{
				if ((this._Precio_Aproximado != value))
				{
					this._Precio_Aproximado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupación", DbType="VarChar(20)")]
		public string Ocupación
		{
			get
			{
				return this._Ocupación;
			}
			set
			{
				if ((this._Ocupación != value))
				{
					this._Ocupación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class cp_ListarUsuarioResult
	{
		
		private int _ID_Usuario;
		
		private string _Usuario;
		
		private string _Ocupación;
		
		private string _Email;
		
		private string _Contraseña;
		
		public cp_ListarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="Int NOT NULL")]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this._ID_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupación", DbType="VarChar(20)")]
		public string Ocupación
		{
			get
			{
				return this._Ocupación;
			}
			set
			{
				if ((this._Ocupación != value))
				{
					this._Ocupación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class cp_ListarVistaMensajeResult
	{
		
		private int _ID_Mensaje;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Mensaje;
		
		public cp_ListarVistaMensajeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Mensaje", DbType="Int NOT NULL")]
		public int ID_Mensaje
		{
			get
			{
				return this._ID_Mensaje;
			}
			set
			{
				if ((this._ID_Mensaje != value))
				{
					this._ID_Mensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(200)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
